version: '3'

services:

  db:
    image: postgres:latest
    cap_add:
      - SYS_NICE
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./data/postgresql/:/var/lib/postgresql